# name: Sync Fork with Upstream

# on:
#   schedule:
#     - cron: '0 0 * * *' # Runs daily at midnight UTC
#   workflow_dispatch: # Allows manual trigger

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0 # Get full history for merge

#       - name: Add upstream remote
#         run: git remote add upstream https://github.com/stackblitz-labs/bolt.diy.git

#       - name: Fetch upstream changes
#         run: git fetch upstream

#       - name: Merge upstream/main into main
#         run: |
#           git checkout main
#           git merge upstream/main --allow-unrelated-histories -X theirs
#           git push origin main
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
